platform :ios, '11.0'

target 'RealmPlugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CryptoSwift', '0.15.0'
  pod 'RealmSwift'
end

target 'RealmPluginTests' do
  use_frameworks!

  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
end
